title: "DCV Designs - Custom 3D Prints"
description: "Modern 3D-printed decor and custom design — built with precision and intention."
url: https://www.dcvdesigns.com
baseurl: ""

# Open Graph / social default image
og_default: /assets/img/og-default.jpg

# Plugins (GitHub Pages-safe)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:slug/
  gallery:
    output: true
    permalink: /gallery/:slug/

# Defaults (make Jekyll Admin show common fields)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

  - scope:
      path: ""
      type: portfolio
    values:
      layout: page
      summary: ""
      category: ""
      tags: []
      photos: []
      detail: ""
      publish_on: ""
      square_url:
      makerworld_url:

  - scope:
      path: ""
      type: gallery
    values:
      layout: page
      summary: ""
      category: ""
      photos: []

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: pretty

# Exclude files/folders from the build
exclude:
  - vendor
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - _config.dev.yml